
TEST=False

BASE_URL = "https://api-testnet.bybit.com" if TEST else "https://api.bybit.com"

WEBSOCKET_BASE_URL = "wss://stream.bybit.com/realtime"

ACCOUNT_TYPE = "SPOT" if TEST else "UNIFIED"


PERCENTOFCAPITAL = 0.02 # in percent



MAXBUYPERCENTOFCAPITAL = 5
MAXSELLPERCENTOFCAPITAL = 5

MINIMUMTRANSACTIONSIZE = 10

SIMTAKEPROFIT = 5
SIMSTOPLOSS = 5


BUYTHRESHOLD = 0.8
SELLTHRESHOLD = 0.4

DATALENGTHFORTRAININGINDAYS = 20
DATALENGTHFORTRADINGINDAYS = 1

INTERVAL = '5'

ALWAYSRETRAIN = False
FORCERETRAINATSTART = True


PERCENTINCREASEMOVEMENTINDICATOR = 2
LOOKAHEADVALUE = 15

PLOTBACKTEST = False
PLOTPROGRESS = True


