
import decimal


TEST=True

BASE_URL = "https://api-testnet.bybit.com" if TEST else "https://api.bybit.com"

WEBSOCKET_BASE_URL = "wss://stream.bybit.com/realtime"

ACCOUNT_TYPE = "SPOT" if TEST else "UNIFIED"


PERCENTOFCAPITAL = 0.02 # in percent



MAXBUYPERCENTOFCAPITAL = 5
MAXSELLPERCENTOFCAPITAL = 10

MINIMUMBTCTRANSACTIONSIZE = decimal.Decimal(0.000048)

TAKEPROFIT = 5
STOPLOSS = 5


BUYTHRESHOLD = 0.8
SELLTHRESHOLD = 0.4

DATALENGTHFORTRAININGINDAYS = 20
DATALENGTHFORTRADINGINDAYS = 1

INTERVAL = '5'

ALWAYSRETRAIN = False
FORCERETRAINATSTART = False


PERCENTINCREASEMOVEMENTINDICATOR = 2
LOOKAHEADVALUE = 2

PLOTBACKTEST = False
PLOTPROGRESS = True
SIMULATETRADE = False


