
BASE_URL = "https://api.bybit.com"

TESTNET_BASE_URL = "https://api-testnet.bybit.com"

WEBSOCKET_BASE_URL = "wss://stream.bybit.com/realtime"


PERCENTOFCAPITAL = 0.02 # in percent
TEST=True
MAXBUYPERCENTOFCAPITAL = 2
MAXSELLPERCENTOFCAPITAL = 2

MINIMUMTRANSACTIONSIZE = 10

SIMTAKEPROFIT = 5
SIMSTOPLOSS = 5


BUYTHRESHOLD = 0.6
SELLTHRESHOLD = 0.4

DATALENGTHFORTRAININGINDAYS = 10
DATALENGTHFORTRADINGINDAYS = 1

INTERVAL = '5'

ALWAYSRETRAIN = False


