FROM mcr.microsoft.com/devcontainers/python:3.7


ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_CACHE_DIR=1

RUN pip install finta
RUN pip install numpy
RUN pip install matplotlib
RUN pip install scikit-learn
RUN pip install pybit
RUN pip install ccxt
RUN pip install pandas
RUN pip install joblib
RUN pip install python-telegram-bot
RUN pip install asciichartpy
RUN pip install python-binance
RUN pip install flask-socketio